# Generated by Django 2.1.15 on 2020-03-08 07:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('link', models.CharField(blank=True, max_length=255)),
                ('file_types', models.CharField(choices=[('R12', 'DXF R12'), ('R13', 'DXF R13'), ('R14', 'DXF R14'), ('R2000', 'DXF R2000'), ('R2004', 'DXF R2004'), ('R2007', 'DXF R2007'), ('R2010', 'DXF R2010'), ('R2013', 'DXF R2013')
                                                         , ('R2018', 'DXF R2018')], max_length=14)),
                ('tags', models.CharField(blank=True, max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
